targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      auto_route_generator:auto_route_generator:
        generate_for:
          - lib/pages/**.dart
