name: Publish to pub.dev

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{secrets.SSH_PRIVATE_KEY}}
          ref: ${{github.ref}}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2

      - name: Install dependencies
        run: flutter pub get

      - name: Publish
        run: flutter pub publish --force # FIXME: Asks for authentication even though it should have used OIDC.
