#!/usr/bin/env bash

target_bump_type=$1 # 'patch' | 'minor' | 'major'
target_changelog_path="$GITHUB_WORKSPACE/CHANGELOG.md"

echo "Target package: $target_package."
echo "Target bump type: $target_bump_type."

if [[ !("$target_bump_type" == 'patch' || "$target_bump_type" == 'minor' || "$target_bump_type" == 'major') ]]; then
  echo "Unsupported target bump type: $target_bump_type."
  exit 1
fi

# 1. Bump the version in pubspec.
cider bump patch

version="$(cider version)"
tag="v$version"
message="chore: bump v$version"

# 2. Generate the changelog and remove the monorepo name.
git cliff \
  --unreleased \
  --tag "$tag" \
  --strip all \
  --prepend "$target_changelog_path"

# 3. Export variables for use in github actions.
echo "OUR_COMMIT_MESSAGE=$message" >>$GITHUB_ENV
echo "OUR_TAGGING_MESSAGE=$tag" >>$GITHUB_ENV

echo "Exported OUR_COMMIT_MESSAGE $message"
echo "Exported OUR_TAGGING_MESSAGE $tag"
